#
# ~/.bashrc
#

alias la='ls -a'
alias ll='ls -lh'
alias lal='ls -alh'
alias ls='ls --color=auto'
alias view='vim -R'
alias steam='STEAM_FRAME_FORCE_CLOSE=1 steam'
alias compton='compton --backend xrender --vsync opengl --paint-on-overlay --config ~/.compton.conf -b'

set -o vi
export EDITOR="vim"
source /usr/share/git/completion/git-completion.bash

PATH="${PATH}:/home/beto/.gem/ruby/2.0.0/bin"

PS1="\[$(tput setaf 8)\][\[$(tput setaf 2)\]\u\[$(tput setaf 8)\]@\[$(tput setaf 2)\]\h \[$(tput bold)\]\[$(tput setaf 4)\]\w\[$(tput sgr0)\]\[$(tput setaf 8)\]]\\$ \[$(tput sgr0)\]"

# Define custom colors specified in ~/.dir_colors
# Generated by "dircolors .dir_colors"
LS_COLORS='no=00:fi=00:di=01;34:ln=01;30:pi=40;33:so=01;35:bd=40;33;01:cd=40;33;01:ex=01;32:*.cmd=01;32:*.exe=01;32:*.com=01;32:*.btm=01;32:*.bat=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.jpg=01;35:*.gif=01;35:*.bmp=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:';
export LS_COLORS

# Color man pages using less
man() {
	env LESS_TERMCAP_mb=$(printf "\e[1;34m") \
		LESS_TERMCAP_md=$(printf "\e[1;34m") \
		LESS_TERMCAP_me=$(printf "\e[0m") \
		LESS_TERMCAP_se=$(printf "\e[0m") \
		LESS_TERMCAP_so=$(printf "\e[1;44;37m") \
		LESS_TERMCAP_ue=$(printf "\e[0m") \
		LESS_TERMCAP_us=$(printf "\e[1;32m") \
		man "$@"
}

